var p = new Point();
console.log("New Object");
console.log(p);
p.setX(3);
console.log("After 3 added");
console.log(p);
p.setY(4);
console.log("After 3 and 4 added");
console.log(p.getX());
console.log("Should be 3");
console.log(p.getY());
console.log("END");
console.log("get point");
console.log(p.getPoint());
